version: '2'

networks:
  app-tier:
    driver: bridge

services:
  rabbitamqp:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-tier


  bootrabbitmq:
    image: springboot-rabbitmq/gs-messaging-rabbitmq
    ports:
      - "80:9055"
    networks:
      - app-tier
#    depends_on:
 #     - "rabbitamqp"
  #  command: ["./wait-for-it.sh", "rabbitamqp:5672", "--", "echo", "rabbitmq is up"]
